[package]
name = "go-algorand"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust2go = "0.4.0"

[build-dependencies]
rust2go = { version = "0.4.0", features = ["build"] }
